name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install and Build
              run: |
                  npm install -g pnpm
                  pnpm install
                  pnpm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  personal_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: ./dist
